export class GlobalResources {
    static getResources() {
        return {
            en: {
                    grower: 'Grower',
                    wetwt:'Wet Weight',
                    wastewt:'Waste Weight',
                    taskname: 'Task Name',
                    tasktype: 'Type',
                    tasknamerequired: 'Select Task.',
                    terminatedpc:'Terminated Plant Count',
                    completedpc:'Completed Plant Count',
                    terminatedreason:'Termination Reason',
                    brand: 'Brand',
                    brandrequired: 'Select Brand.',
                    subbrand: 'Sub-Brand',
                    growerrequired: 'Select Grower.',
                    strain: 'Strain',
                    strainrequired: 'Select Strain.',
                    lotno: 'Lot No.',
                    lotnorequired: 'Enter state lot number.',
                    lottype: 'Lot Type',
                    lotminlength: 'State lot number should be greater than 6 characters.',
                    lottyperequired: 'Select lot type.',
                    trimmed: 'Trimmed',
                    lotentrytrimmed: 'Trimmed(at purchase)',
                    measure: '(Grams)',
                    mandatory: '*',
                    employee: 'Employee',
                    employeerequired: 'Select employee.',
                    priority: 'Priority',
                    ipbinwt:'Bin Weight',
                    eststartdate: 'Est. Start Date',
                    estenddate: 'Est. End Date',
                    enddaterequired: 'Select estimated end date.',
                    estimatedhrs: 'Est. Hrs.',
                    estimatedhrsrequired: 'Enter esitimated hours.',
                    startdaterequired: 'Est. Start Date is required.',
                    actualstartdate: 'Actual Start Date',
                    actualenddate: 'Actual End Date',
                    actualhrs: 'Actual Hrs (HH:MM:SS)',
                    revHrs:'Review Hrs (HH:MM:SS)',
                    datecomparevalidation: 'Task start date should be less than task end date.',
                    notifymanager: 'Notify Manager',
                    notifyemployee: 'Notify Employee',
                    comment: 'Comment',
                    commentmaxlength: 'Maximum length of comment is 500 charachers.',
                    positiveintegersallowed: 'allowed only positive intergers/decimals.',
                    misccost: 'Misc. Cost(if any)',
                    orderno: 'Order No.',
                    ordernorequired: 'Enter order number.',
                    wtoflot: 'Weight of lot',
                    startdate: 'Start Date',
                    enddate: 'End Date',
                    status: 'Status',
                    select: 'Select',
                    retailers: 'Retailers',
                    retailer: 'Retailer',
                    budweight: 'Bud Material Weight',
                    budweightrequired: 'Enter bud material weight.',
                    jointsweight: 'Joints Material Weight',
                    jointsweightrequired: 'Enter joints material weight.',
                    oilweight: 'Oil Material Weight',
                    oilweightrequired: 'Enter oil material weight.',
                    wasteweight: 'Waste Material Weight',
                    wasteweightrequired: 'Enter waste material weight.',
                    skewed: 'Skew Type',
                    debit: 'Debit',
                    credit: 'Credit',
                    balance: 'Un-Assigned',
                    nexttask: 'Next Task Name',
                    action: 'Action',
                    assignwt: 'Assigned Wt.',
                    time: 'Time',
                    bin:'Bin Name',
                    emprate: 'Rate/Hr.',
                    empestcost: 'Est. Cost',
                    assignedwt: 'Assigned Weight',
                    endtime: 'End Time',
                    applicationmsg: 'Application Message',
                    plantcountmore:'Completed Plant Count Greater Than Assigned Plant Count',
                    serverError: 'Something went wrong at server side.',
                    unit: 'Unit',
                    deliverydate: 'Delivery Date',
                    zeronotallow: 'Value should be greater than 0.',
                    pkgtype: 'Package Type',
                    pkgsize: 'Package Size',
                    orderqty: 'Order Qty',
                    requirewt: 'Require Wt',
                    assignqty: 'Assign Qty',
                    lotdetails: 'Lot Details',
                    itemqty: 'Item Qty',
                    norecordsfound: 'No Records Found.',
                    listgramunit: '(g)',
                    completedqty: 'Completed Qty',
                    revqty: 'Rev. Qty',
                    selectedqty: 'Selected Qty',
                    requiredqty: 'Require Qty',
                    availqty: 'Available Qty',
                    createddate: 'Created Date',
                    uniqueid: 'Unique Id',
                    savesuccess: 'Details has been saved successfully.',
                    isrequiredmsg: ' is required.',
                    pastdatetask: 'Task will be get created for past date.',
                    maxlengthexceed: 'Max length exceeded.',
                    invalidinput: 'Invalid input.',
                    actiontaker: 'Action Taker',
                    actiondate: 'Action Date',
                    pkgcode: 'Package Code',
                    tppkgcode: 'TP Pkg. Code',
                    tppkgtype: 'TP Pkg. Type',
                    tppkgsize: 'TP Pkg. Size',
                    oilpkgcode: 'Oil Pkg. Code',
                    pkgdetails: 'Pkg Details',
                    srno: 'Sr. No.',
                    pkgcoderequire: 'Package code is required.',
                    selectall: 'Select All',
                    assignedqty: 'Assign Qty',
                    brandlablerepcount: 'Brand and Lable Replace Count',
                    qafailcomment: 'QA Fail Comment',
                    thc: 'THC%',
                    cbd: 'CBD%',
                    thca: 'THCA%',
                    cbda: 'CBDA%',
                    percentage: '%',
                    validemail: 'Email is invalid',
                    growersavedsuccess: 'Grower saved successfully',
                    groweralreadyexist: 'Grower already exists',
                    city: 'City',
                    country: 'Country',
                    state: 'State',
                    cityrequired: 'Enter City',
                    countryrequired: 'Select Country',
                    staterequired: 'Select State',
                    ManagerDashboard: 'Manager Dashboard',
                    totalthc: 'Total THC%',
                    lotnotavailable: 'Lots are not available.',
                    oilpkgnotavailable: 'Oil Packages are not available.',
                    pkgcompletedqty: 'Pkg. Completed Qty',
                    pkgcompletedwt: 'Pkg. Completed Wt.',
                    lotcompletedwt: 'Lot Completed Wt.',
                    lotbalancedwt: 'Lot Balanced Wt.',
                    completedwt: 'Completed Wt.',
                    balancedwt: 'Balanced Wt.',
                    pkg: 'Pkg.',
                    mixlotpkg: 'Mixed Lot Pkg.',
                    selectedwt: 'Selected Wt.',
                    no: 'No.',
                    balancedqty: 'Balanced Qty',
                    nolotselected: 'No lot selected.',
                    nopkgselected: 'No pkg. selected.',
                    selectedjointsqty: 'Selected Joints Qty',
                    availjointsqty: 'Avail. Joints Qty',
                    selectedtubeqty: 'Selected Tube Qty',
                    assignpkgqty: 'Assign Pkg. Qty',
                    assignedpkgqty: 'Assigned Pkg. Qty',
                    requiredjointsqty: 'Required Joints Qty',
                    requiredtubeqty: 'Required Tube Qty',
                    assignedjointsqty: 'Assigned Joints Qty',
                    saveconfirm: 'Are you sure that you want to proceed?',
                    mixpkgdetails: 'Mix Pkg. Details',
                    task: 'Task',
                    assignby: 'Assigned By',
                    lastactiondate: 'Last Action Date',
                    lot: 'Lot',
                    expdeliverydate: 'Exp. Delivery Date',
                    IsActiveFlag: 'Is Active',
                    negativenotallow: 'Only positive digits are allowed.',
                    expreturndate: 'Exp. Return Date',
                    outwarddate: 'Outward Date',
                    strainnotpresent: 'Strain is deleted or is inactive.',
                    growernotpresent: 'Grower is deleted or is inactive.',
                    genetics: 'Genetics',
                    pkgSize: 'Pkg. Size',
                    pkgQty: 'Pkg. Qty',
                    order: 'Order #',
                    assignedtubeqty: 'Assigned Tube Qty.',
                    completedtubeqty: 'Completed Tube Qty.',
                    balancedtubeqty: 'Balanced Tube Qty.',
                    completedjointsqty: 'Completed Joints Qty',
                    balancedjointsqty: 'Balanced Joints Qty',
                    labelcolon: ':',
                    selectmixpkg: 'Select Mix Pkg.',
                    growerdeletedorinactive: 'Grower is deleted or is inactive.',
                    straindeletedorinactive: 'Strain is deleted or is inactive.',
                    requiredtubesqty: 'Required Tubes Qty.',
                    mixpkgno: 'Mix Pkg. No.',
                    orderid: 'Order Id',
                    assignedQty: 'Assigned Qty.',
                    more: 'more',
                    othermaterial: 'Other Material',
                    budmaterial: 'Bud Material',
                    jointsmaterial: 'Joints Material',
                    reqtubes: 'Req. Tubes',
                    // Added by DEVDAN :: 01-Oct-2018 :: For duplicate email address
                    duplicateEmail: 'Pimary and Secondary emails should not be same',
                    passwordRequired: 'Please enter valid password.',
                    badpassword: 'Provided password is incorrect.',
                    sessiontimeoutwarning: 'Session Timeout Warning',
                    sessionabouttoexpire: 'Your session is about to expire!',
                    staysignin: 'Do you want to stay signed in?',
                    actualworkmins: 'Actual Mins',
                    tubecompleted: 'Tube Completed',
                    assigntubes: 'Assign Tubes',
                     // Added by Devdan :: 13-Nov-2018 :: Resource for Minute and Second value error
                     maxMinSecValue: 'Value should not be greater than 59',
                     usablewt: 'Usable Wt',
                     elapsedtimewithformat: 'Elapsed Time (HH:MM:SS)',
                     packageSize: 'Package Size',
                     readyforlabeling: 'Ready for Labeling',
                     strainDetails: 'Strain Details',
                     sufixS: '(s)',
                     listgramunits: 'g',
                     size: 'Size',
                     units: 'Units',
                     gramUnit: 'g',
                     total: 'Total',
                     taskCategory:'Task Category'
                }
            };
    }
}
