export class MastersResource {
    static getResources() {
        return {
            en: {
                newlabel: {
                    pageheading: 'Add New Bin',
                    taskType:'Task Type',
                    binNo:'Bin Number',
                    strain:'Cultivar',
                    skewType:'Skew Type',
                    lightDept:'Light Dept',
                    trimmingMethod:'Trimming Method',
                    header:'Bins List',
                    newlabelsavedsuccess:'Successfully saved',
                    deleteLabelMsg: 'Do you want to delete this Bin?',
                    newlabeldeletedsuccess:'Bin deleted successfully',
                    labeldeactivatesuccess:'Bin deactivated',
                 labelactivatesuccess:'Bin activated',
                 activeLabelMsg: 'Do you want to activate this Bin?',
                 deactivateLabelMsg: 'Do you want to inactivate this Bin?',
                 updated: 'Updated Successfully',
                 duplicate:'Duplicate Bin',
                 binisbeingused:'This bin is in use so you cannot delete this bin'
                },
                newproductype: {
                    pageheading: 'Add New Product Type',
                    brand: 'Brand',
                    brandrequired: 'Brand Required',
                    subbrand: 'Sub Brand',
                    subbrandrequired: 'Sub Brand Required',
                    strain: 'Cultivar ',
                    strainrequired: 'Cultivar  Required',
                    skewtype: 'Skew Type',
                    skewtyperequired: 'Skew Type Required',
                    packagetype: 'Package Type',
                    packagetyperequired: 'Package Type Required',
                    packageunit: 'Package Unit (lb)',
                    packageunitrequired: 'Package Unit Required',
                    packageUnitLength: 'Maximum 5 digits are allowed.',
                    packageitemqty: 'Package Item Qty',
                    packageitemqtyrequired: 'Package Item Qty Required',
                    packageItemQtyLength: 'Maximum 5 digits are allowed.',
                    packagelbl: 'Package Label',
                    packagelblrequired: 'Package Lable Required',
                    packageLableLength: 'Maximum 50 characters are allowed.',
                    newproductsavedsuccess: 'New Product Type Details Saved Successfully.',
                    prodcttypealreadyexist: 'This product type already exist',
                    addnewbrand: 'Add New Brand',
                    addsubbrand: 'Add New Sub Brand',
                    addstrain: 'Add New Cultivar ',
                    addpackagetype: 'Add New Package Type',
                    createddate: 'Created Date',
                    headingproducttypelist: 'New Product Type List',
                    prodcttypedeletesuccess: 'Product type deleted successfully.',
                    producttypedeactivatesuccess: 'Product type inactivaed successfully.',
                    producttypeactivatesuccess: 'Product type activaed successfully.',
                    producttypeisassigned: 'Can not delete this product type. It is in use.',
                    producttypeactiveinactive: 'Can not inactivate this product type. It is in use.',
                    cannotinsert: 'Can not save product type details. Might be something is not available now. Please check.',
                    brandnotpresent: 'Brand is deleted or is inactive.',
                    subbrandnotpresent: 'Sub Brand is deleted or is inactive.',
                    strainnotpresent: 'Cultivar  is deleted or is inactivated.',
                    pkgtypenotpresent: 'Package type is deleted or is inactive.',
                    skewnotpresent: 'Skew is deleted or is inactive.',
                    packageunitval: 'Package unit qty should be greater than zero.',
                    packageitemqtyval: 'Package item qty should be greater than zero.',

                    // add swapnil 01-April-2019 for view links
                    viewbrands: 'View All Brands',
                    viewsubbrands: 'View All Sub-Brands',
                    viewstrain: 'View All Cultivar',
                    viewpackagetype: 'View All Package Types',
                    PackageUnitPrice:'Package Unit Price',
                    PackageUnitPricerequired:'Package Unit Price Required',
                    MeasureOfUnit:'Measure Of Unit'
                    


                },
                addnewsection: {
                    pageheading: 'Add New Section',
                    tableheading: 'Section List',
                    newsectionsavedsuccess:'section saved successfully',
                    deleteSectionMsg: 'Do you want to delete this Section?',
                    newsectiondeletedsuccess:'section deleted successfully',
                   sectionisassigned: 'section is in use',
                 sectiondeactivatesuccess:'section is deactivated',
                 sectionactivatesuccess:'section is activated',
                 activeSectionMsg: 'Do you want to activate this Section?',
                 deactivateSectionMsg: 'Do you want to inactivate this Section?',
                    duplicateSection: 'Duplicate Section',
                    alreadydeleted: 'Already Deleted',
                    updated: 'Updated Successfully'

                },
                addNewRawMaterial: {
                    newRawMaterialavedsuccess:'Raw Material saved successfully',
                    BinWtMoreWtThanReceivedWt :'Total Recevied Weight is not equal to Total Bins Weight',
                    binsNotAvail:'Bins Not Avilable',
                    growerdeleted:'Grower Deleted',
                    deleteARMMsg: 'Do you want to delete this Raw Material?',
                    newARWdeletedsuccess:'Raw Material deleted successfully',
                    binisinuse:'Bin Is In Processed State',
                },
                addnewbrand: {
                    pageheading: 'Add New Brand',
                    pageheadinglist: 'Brand List',
                    enterbrand: 'Brand Name',
                    brand: 'Brand Name',
                    subbrand: 'Sub Brand Name',
                    brandrequired: 'Brand Required',
                    brandLength: 'Must not more than 50 charachters',
                    enterdescription: 'Brand Description',
                    description: 'Description',
                    descriptionrequired: 'Description Required',
                    descriptionLength: 'Must not more than 500 charachters',
                    newbrandsavedsuccess: 'New brand saved successfully.',
                    brandalreadyexist: 'This brand already exist',
                    headingbrandlist: 'Brand List',
                    branddeletesuccess: 'Brand deleted successfully.',
                    branddeactivatesuccess: 'Brand inactivated successfully.',
                    brandactivatesuccess: 'Brand activated successfully.',
                    brandinuse: 'Can not delete this brand. It is in use.',
                    brandhavetaskactive: 'Can not inactivate this brand. It is in use.',
                    noinsert: 'Can not insert new record for this brand.',
                    brandnotpresent: 'Brand is deleted or is inactive',
                    noupdate: 'Can not update this brand. Might be it does not exist.',
                    notactivated: 'Can not activate this brand. Might be it does not exist.',
                    notinactivated: 'Can not inactivate this brand. Might be it does not exist.',
                    notdeleted: 'Can not delete this brand. Might be it does not exist.'
                },

                addnewsubbrand: {
                    pageheading: 'New Sub Brand',
                    selectbrand: 'Select Brand Name',
                    brandrequired: 'Select Brand',
                    entersubbrand: 'Sub Brand Name',
                    subbrand: 'Sub Brand',
                    subbrandrequired: 'Sub Brand Required',
                    subbrandLength: 'Must not more than 50 charachters',
                    descriptionLength: 'Must not more than 100 charachters',
                    description: 'Sub Brand Description',
                    enterdescription: 'Sub Brand Description',
                    headingsubbrandlist: 'Sub Brand List',
                    newsubbrandsavedsuccess: 'New sub brand saved successfully.',
                    subbrandalreadyexist: 'This sub brand already exist',
                    subbrandinuse: 'Can not delete this sub brand. It is in use.',
                    cannotinsert: 'Can not save sub brand details. Might be brand is not available now. Please check.',
                    subbranddeletesuccess: 'Sub brand deleted successfully.',
                    subbranddeactivatesuccess: 'Sub brand inactivated successfully.',
                    subbrandactivatesuccess: 'Sub brand activated successfully.',
                    brandnotpresent: 'Brand is deleted or is inactive',
                    noupdate: 'Can not update this sub brand. Might be it does not exist.',
                    notactivated: 'Can not activate this sub brand. Might be it does not exist.',
                    notinactivated: 'Can not inactivate this sub brand. Might be it does not exist.',
                    notdeleted: 'Can not delete this sub brand. Might be it does not exist.',
                    brandIsInactive: 'Can not activate this sub brand. Might be brand is inactive.'
                },

                addnewstrain: {
                    pageheading: 'New Cultivar ',
                    enterstraintype: 'Cultivar  Type',
                    straintype: 'Cultivar  Type',
                    straintyperequired: 'Select Cultivar  Type',
                    enterstrain: 'Cultivar  Name',
                    strain: 'Cultivar ',
                    strainrequired: 'Cultivar  Required',
                    strainLength: 'Must not more than 50 charachters',
                    description: 'Cultivar  Description',
                    enterthc: 'THC',
                    thc: 'THC',
                    thcrequired: 'THC Required',
                    thcLength: 'Must not more than 5 charachters',
                    enterthca: 'THCA',
                    thca: 'THCA',
                    thcarequired: 'THCA Required',
                    thcaLength: 'Must not more than 5 charachters',
                    entercbd: 'CBD',
                    cbd: 'CBD',
                    cbdrequired: 'CBD Required',
                    cbdLength: 'Must not more than 5 charachters.',
                    entercbda: 'CBDA',
                    cbda: 'CBDA',
                    cbdarequired: 'CBDA Required',
                    cbdaLength: 'Must not more than 5 charachters.',
                    entertotal: 'Total',
                    total: 'Total',
                    totalrequired: 'Total Required',
                    totalLength: 'Must not more than 5 charachters',
                    newstrainsavedsuccess: 'Cultivar  saved successfully.',
                    strainalreadyexist: 'This Cultivar  already exist',
                    strainActivated: 'Cultivar  activated successfully.',
                    strainInactivated: 'Cultivar  inactivated successfully.',
                    deletestrainmsg: 'Do you want to delete this Cultivar ?',
                    activestrainmsg: 'Do you want to activate this Cultivar ?',
                    deactivatestrainmsg: 'Do you want to inactivate this Cultivar ?',
                    genetics: 'Binomial Name',
                    geneticsrequired: 'Species Required.',
                    straintypenotpresent: 'Cultivar  type is deleted or is inactive.',
                    geneticsnotpresent: 'Species is deleted or is inactive.',
                    strainDeletedSuccess: 'Cultivar  deleted successfully.',
                    noupdate: 'Can not update this starin. Might be it does not exist.',
                    notdeleted: 'Can not delete this Cultivar . Might be it does not exist.',
                    notactivated: 'Can not activate this Cultivar . Might be it does not exist.',
                    notinactivated: 'Can not inactivate this Cultivar . Might be it does not exist.',
                    cannotinsert: 'Can not save Cultivar  details. Might be Cultivar  type is not available now. Please check.',
                    straintypeOrGeneticsIsInactive: 'Can not activate this Cultivar . Might be Cultivar  type or Species is inactive.',
                    straintypedeleted: 'Can not perform action, Cultivar  type is deleted.',
                    viewaddgenetic: 'View/Add Species',
                },

                addnewstraintype: {
                    pageheading: 'New Cultivar  Type',
                    enterstraintype: 'Cultivar  Type Name',
                    straintyperequired: 'Cultivar  Type Required',
                    straintypeLength: 'Must not more than 50 charachters',
                    enterdescription: 'Cultivar  Type Description',
                    descriptionrequired: 'Description Type Required',
                    descriptionLength: 'Must not more than 500 charachters',
                    newstraintypesavedsuccess: 'Cultivar  type  saved successfully.',
                    newstraintypeinactivated: 'Cultivar  type inactivated successfully.',
                    newstraintypeactivated: 'Cultivar  type activated successfully.',
                    newstraintypedeleted: 'Cultivar  type deleted successfully.',
                    straintypealreadyexist: 'This Cultivar  type already exist',
                    straintypeisassigned: 'Can not delete this Cultivar  type. It is in use.',
                    noupdate: 'Can not update this Cultivar  type. Might be it does not exist.',
                    notactivated: 'Can not activate this Cultivar  type. Might be it does not exist.',
                    notinactivated: 'Can not inactivate this Cultivar  type. Might be it does not exist.',
                    notdeleted: 'Can not delete this Cultivar  type. Might be it does not exist.',
                    strainIsInactive: 'Can not activate this Cultivar  type. May be Cultivar  is inactive.'
                },

                addnewpackagetype: {
                    pageheading: 'Add New Package Type',
                    enterpackagetype: 'Package Type Name',
                    packagetype: 'Package Type',
                    packagetyperequired: 'Package Type Required',
                    packagetypeLength: 'Must not more than 50 charachters',
                    enterdescription: 'Enter Descripion',
                    description: 'Description',
                    descriptionrequired: 'Description Required',
                    descriptionLength: 'Must not more than 500 charachters',
                    newpackagetypesavedsuccess: 'New package type saved successfully.',
                    packagetypealreadyexist: 'This packagetype already exist',
                    headingpackagetype: 'Package Type List',
                    packagetypedeletesuccess: 'Package type deleted successfully.',
                    packagetypedeactivatesuccess: 'Package type inactivated successfully.',
                    packagetypeactivatesuccess: 'Package type activated successfully.',
                    packagetypeinuse: 'Can not delete. This package type is in use.',
                    packagetypehavetaskactive: 'Can not inactivate. This package type is in use.',
                    noupdate: 'Can not update this package type. Might be it does not exist.',
                    notactivated: 'Can not activate this package type. Might be it does not exist.',
                    notinactivated: 'Can not inactivate this package type. Might be it does not exist.',
                    notdeleted: 'Can not delete this package type. Might be it does not exist.'
                },

                grower: {
                    pageheading: 'Add New Supplier',
                    growerlist: 'Supplier List',
                    client: 'Client Name',
                    grower: 'Supplier Name',
                    growerLength: 'Maximun 30 characters are allowed',
                    officephone: 'Office Phone',
                    officephoneLength: 'Maximum 15 digits are allowed',
                    cellphone: 'Cell Phone',
                    faxphone: 'Fax Phone',
                    primaryemail: 'Primary Email',
                    secondaryemail: 'Secondary Email',
                    emailLength: 'Maximum 50 characters are allowed',
                    contactperson: 'Contact Person',
                    contactpersonLength: 'Maximum 150 characters are allowed',
                    address: 'Address',
                    addressLength: 'Maximum 500 characters are allowed',
                    city: 'City',
                    country: 'Country',
                    state: 'State',
                    zipcode: 'Zip Code',
                    zipcodeLength: 'Zip code should not more than 9 digits',
                    latitude: 'Latitude',
                    longitude: 'Longitude',
                    latitudeLength: 'Maximum 20 characters are allowed',
                    description: 'Description',
                    descriptionLength: 'Maximum 500 characters are allowed',
                    clientrequired: 'Select Client',
                    officephonerequired: 'Enter Office Phone',
                    addressrequired: 'Enter Address',
                    cityrequired: 'Select City',
                    countryrequired: 'Select Country',
                    staterequired: 'Select State',
                    zipcoderequired: 'Enter Zip Code',
                    validemail: 'Enter Valid Email',
                    growerrequired: 'Please enter Supplier',
                    growersavedsuccess: 'Supplier details saved successfully.',
                    groweralreadyexist: 'Supplier already exist.',
                    inactivated: 'Supplier inactivated successfully.',
                    activated: 'Supplier activated successfully.',
                    deletedSuccess: 'Supplier deleted successfully.',
                    noupdate: 'Can not update this Supplier. Might be it does not exist.',
                    cannotInactivate: 'Can not inactivate this Supplier. Might be it does not exist.',
                    cannotActivate: 'Can not activate this Supplier. Might be it does not exist.',
                    cannotdelete: 'Can not delete this Supplier. Might be it does not exist.',
                    growerdetails: 'Supplier Details'
                },
                addnewcountry: {
                    pageheading: 'Add New Country',
                    countrylist: 'Country List',
                    countryrequired: 'Enter Country',
                    country: 'Country Name',
                    countryexists: 'Country already exists',
                    countrysuccess: 'Country added successfully.'
                },
                addnewstate: {
                    pageheading: 'Add New State',
                    Statelist: 'State List',
                    state: 'State Name',
                    country: 'Country Name',
                    countryrequired: 'Country Required',
                    staterequired: 'State Required',
                    stateexists: 'State already exists',
                    statesuccess: 'State added successfully'

                },
                addnewcity: {
                    pageheading: 'Add New City',
                    citylist: 'City, State, Country List',
                    addnewcountry: 'Add New Country',
                    addnewstate: 'Add New State',
                    citysuccess: 'City added successfully',
                    cityexists: 'City already exist'
                },

                tpprocessor: {
                    pageheading: 'Add New TP Processor',
                    tpprocessorsuccess: 'TP processor saved successfully.',
                    tpprocessorexists: 'TP processor already exist.',
                    primaryemailrequired: 'Primary mail required',
                    tpprocessorlist: 'TP Processor List',
                    client: 'Client Name',
                    tpprocessorname: 'TP Processor',
                    officephone: 'Office Phone',
                    officephoneLength: 'Maximum 15 digits are allowed',
                    cellphone: 'Cell Phone',
                    faxphone: 'Fax Phone',
                    primaryemail: 'Primary Email',
                    secondaryemail: 'Secondary Email',
                    emailLength: 'Maximum 50 characters are allowed',
                    contactperson: 'Contact Person',
                    contactpersonLength: 'Maximum 150 characters are allowed',
                    address: 'Address',
                    addressLength: 'Maximum 500 characters are allowed',
                    city: 'City',
                    country: 'Country',
                    state: 'State',
                    zipcode: 'Zip Code',
                    zipcodeLength: 'Zip code should not more than 9 digits',
                    latitude: 'Latitude',
                    longitude: 'Longitude',
                    latitudeLength: 'Maximum 20 characters are allowed',
                    description: 'Description',
                    descriptionLength: 'Must not more than 100 charachters',
                    clientrequired: 'Select Client',
                    officephonerequired: 'Enter Office Phone',
                    addressrequired: 'Enter Address',
                    cityrequired: 'Select City',
                    countryrequired: 'Select Country',
                    staterequired: 'Select State',
                    zipcoderequired: 'Enter Zip Code',
                    validemail: 'Enter Valid Email',
                    tpprocessorrequired: 'Enter TP processor name',
                    tpprocessorLength: 'Maximum 30 characters are allowed',
                    expectedYeild: 'Expected Yeild (%)',
                    expectedYeildMaxLength: 'Maximum 100% Expected Yield is allowed.',
                    expectedYeildMinLength: 'Expected Yeild should be greater than 0',
                    expectedYeildrequired: 'Expected Yeild is Required',
                    materialaspayment: '% Of Material As Payment',
                    materialaspaymentrequired: 'Material as payment Required',
                    materialaspaymentMaxLength: 'Maximum 100 material payment is allowed.',
                    materialaspaymentMinLength: 'Material payment should be greater than 0',
                    exrturnaroundtime: 'Expected Turnaround Days',
                    exrturnaroundtimerequired: 'Exp Turnaround Time Required',
                    expturnaroundtimeMinLength: 'Exp turnaround time should be positive value.',
                    inactivated: 'TP processor inactivated successfully.',
                    activated: 'TP processor activated successfully.',
                    deletedSuccess: 'TP processor deleted successfully.',
                    noupdate: 'Can not update this TP Processor. Might be it does not exist.',
                    cannotInactivate: 'Can not inactivate this TP Processor. Might be it does not exist.',
                    cannotActivate: 'Can not activate this TP Processor. Might be it does not exist.',
                    cannotdelete: 'Can not delete this TP Processor. Might be it does not exist.',
                    inuse: 'Can not delete this TP processor. It is in use.',
                    duplicateEmail: 'Secondary email is same as primary email.',
                    tpprocessordetails: 'TP Processor Details',
                    tpprocessorname1: 'TP Processor Name'
                },

                retailer: {
                    pageheading: 'Add New Retailer',
                    primaryemailrequired: 'Primary Mail Required',
                    retailerlist: 'Retailer List',
                    retailertyperequired: 'Select Retailer Type',
                    client: 'Client Name',
                    retailertype: 'Retailer Type',
                    retailer: 'Retailer Name',
                    licenseno: 'License No',
                    ubino: ' UBI No',
                    officephone: 'Office Phone',
                    cellphone: 'Cell Phone',
                    faxphone: 'Fax Phone',
                    primaryemail: 'Primary Email',
                    secondaryemail: 'Secondary Email',
                    contactperson: 'Contact Person',
                    address: 'Address',
                    city: 'City',
                    country: 'Country',
                    state: 'State',
                    zipcode: 'Zip Code',
                    latitude: 'Latitude',
                    longitude: 'Longitude',
                    description: 'Description',
                    clientrequired: 'Select Client',
                    officephonerequired: 'Enter Office Phone',
                    addressrequired: 'Enter Address',
                    cityrequired: 'Select City',
                    countryrequired: 'Select Country',
                    staterequired: 'Select State',
                    zipcoderequired: 'Enter Zip Code',
                    validemail: 'Enter Valid Email',
                    retailerrequired: 'Please Enter Retailer',
                    licenserequired: 'Please Enter License',
                    ubinorequired: 'Please Enter UBI No',
                    retailersuccess: 'Retailer added successfully',
                    customersuccess:'Customer added successfully',
                    retailerexists: 'Retailer already exist',
                    customerexists:'Customer already exist',
                    // Added by DEVDAN :: 01-Oct-2018 :: Added messaged for data manipulation
                    inactivated: 'Retailer inactivated successfully.',
                    custinactivated:'Customer inactivated successfully.',
                    custactivated:'Customer activated successfully.',
                    activated: 'Retailer activated successfully.',
                    deletedSuccess: 'Retailer deleted successfully.',
                    custdeletedSuccess:'Customer deleted successfully.',
                    noupdate: 'Can not update this Retailer. Might be it does not exist.',
                    cannotInactivate: 'Can not inactivate this Retailer. Might be it does not exist.',
                    custcannotInactivate: 'Can not inactivate this Customer. Might be it does not exist.',
                    cannotActivate: 'Can not activate this Retailer. Might be it does not exist.',
                    custcannotActivate: 'Can not activate this Customer. Might be it does not exist.',
                    cannotdelete: 'Can not delete this Retailer. Might be it does not exist.',
                    custcannotdelete: 'Can not delete this Customer. Might be it does not exist.',
                    inuse: 'Can not delete this Retailer. It is in use.',
                    custinuse: 'Can not delete this Customer. It is in use.',
                    updateSuccess: 'Retailer updated successfully.',
                    custupdateSuccess: 'Customer updated successfully.',
                    phoneLength: 'Maximum 15 digits are allowed',
                    updateFailure: 'Can not update this Retailer. Might be it does not exist.',
                    custupdateFailure: 'Can not update this Customer. Might be it does not exist.',
                    // End of Added by DEVDAN
                },
                flc:{
                    contractorsuccess:'FLC added successfully',
                    updateSuccess: 'FLC updated successfully.',
                    inactivated:'FLC inactivated successfully.',
                    flcinactivated:'FLC inactivated successfully.',
                    activated: 'FLC activated successfully.',
                    alreadydlt:'FLC Already Deleted',
                    deletedSuccess: 'FLC deleted successfully.',
                    cannotActivate: 'Can not activate this FLC. Might be it does not exist.',
                    cannotdelete: 'Can not delete this FLC. Might be it does not exist.',
                    cannotInactivate: 'Can not inactivate this FLC. Might be it does not exist.',
                    inuse: 'Can not delete this FLC. It is in use.',
                    duplicate:'Duplicate record found'
                },
                ptr:{
                    contractorsuccess:'Plant Termination Reason added successfully',
                    updateSuccess: 'Plant Termination Reason updated successfully.',
                    inactivated:'Plant Termination Reason inactivated successfully.',
                    ptrinactivated:'Plant Termination Reason inactivated successfully.',
                    activated: 'Plant Termination Reason activated successfully.',
                    alreadydlt:'Plant Termination Reason Already Deleted',
                    deletedSuccess: 'Plant Termination Reason deleted successfully.',
                    cannotActivate: 'Can not activate this Plant Termination Reason. Might be it does not exist.',
                    cannotdelete: 'Can not delete this Plant Termination Reason. Might be it does not exist.',
                    cannotInactivate: 'Can not inactivate this Plant Termination Reason. Might be it does not exist.',
                    inuse: 'Can not delete this Plant Termination Reason. It is in use.',
                    duplicate:'Duplicate record found',
                    AlreadyDeleted:'Plant Termination Reason Already Deleted'
                },
                chemicalmaster:{
                    success:"Chemical Type Saved Successfully ",
                    updated:"Chemical Type Updated Successfully ",
                    inactivated:'Chemical Type inactivated successfully.',
                    activated: 'Chemical Type activated successfully.',
                    alreadydlt:'Chemical Type Already Deleted',
                    deletedSuccess: 'Chemical Type deleted successfully.',
                    cannotActivate: 'Can not activate this Chemical Type. Might be it does not exist.',
                    cannotdelete: 'Can not delete this Chemical Type. Might be it does not exist.',
                    cannotInactivate: 'Can not inactivate this Chemical Type. Might be it does not exist.',
                    inuse: 'Can not delete this Chemical Type. It is in use.',
                    duplicate:'Duplicate record found',
                    AlreadyDeleted:'Chemical Type Already Deleted'
                },

                chemicalpurchase:{
                    success:"Chemical Purchase Saved Successfully ",
                    updated:"Chemical Purchase Updated Successfully ",
                    inactivated:'Chemical Purchase inactivated successfully.',
                    activated: 'Chemical Purchase activated successfully.',
                    alreadydlt:'Chemical Purchase Already Deleted',
                    deletedSuccess: 'Chemical Purchase deleted successfully.',
                    cannotActivate: 'Can not activate this Chemical Purchase. Might be it does not exist.',
                    cannotdelete: 'Can not delete this Chemical Purchase. Might be it does not exist.',
                    cannotInactivate: 'Can not inactivate this Chemical Purchase. Might be it does not exist.',
                    inuse: 'Can not delete this Chemical Purchase. It is in use.',
                    duplicate:'Duplicate record found',
                    AlreadyDeleted:'Chemical Purchase Already Deleted'
                },
                

         addnewclient: {
                    pageheading: 'Add New Client',
                    countrylist: 'City List',
                    clientlist: 'Client List',
                    client: 'Client Name',
                    contactperson: 'Contact Person',
                    utctimezone: 'UTC Time Zone',
                    officephone: 'Office Phone',
                    cellphone: 'Cell Phone',
                    faxphone: 'Fax Phone',
                    primaryemail: 'Primary Email',
                    secondaryemail: 'Secondary Email',
                    address: 'Address',
                    city: 'City',
                    country: 'Country',
                    state: 'State',
                    zipcode: 'Zip Code',
                    latitude: 'Latitude',
                    longitude: 'Longitude',
                    description: 'Description',
                    officephonerequired: 'Enter Office Phone',
                    addressrequired: 'Enter Address',
                    cityrequired: 'Select City',
                    countryrequired: 'Select Country',
                    staterequired: 'Select State',
                    zipcoderequired: 'Enter Zip Code',
                    utctimezonerequired: 'Select UTC Time Zone',
                    clientrequired: 'Enter Client',
                    primaryemailrequired: 'Primary Email Required',
                    clientsuccess: 'Client added successfully',
                    clientexists: 'Client already exist',
                    contactpersonrequired: 'Enter Contact Person',
                    dateformat: 'Date Format',
                    dateformatrequied: 'Select Date Format'
                },
                addnewemployee: {
                    pageheading: 'Add New Employee',
                    clientname: 'Client Name',
                    clientnamerequired: 'Client Name Required',
                    firstname: 'Employee First Name',
                    firstnameshort: 'Emp First Name',
                    firstnamerequired: 'Employee First Name Required',
                    middlename: 'Employee Middle Name',
                    middlenamerequired: 'Employee Middle Name Required',
                    lastname: 'Employee Last Name',
                    lastnameshort: 'Emp Last Name',
                    lastnamerequired: 'Employee Last Name Required',
                    gender: 'Gender',
                    genderrequired: 'Gender Required',
                    dob: 'DOB',
                    dobrequired: 'DOB Required',
                    cellphone: 'Cell Phone',
                    cellphonerequired: 'Cell Phone Required',
                    homephone: 'Home Phone',
                    homephonerequired: 'Home Phone Required',
                    primaryemail: 'Primary Email',
                    primaryemailrequired: 'Primary Email Required',
                    secondaryemail: 'Secondary Email',
                    secondaryemailrequired: 'Primary Email Required',
                    address: 'Address',
                    addressrequired: 'Address Required',
                    country: 'Country',
                    countryrequired: 'Country Required',
                    state: 'State',
                    staterequired: 'State Required',
                    city: 'City',
                    cityrequired: 'City Required',
                    zipcode: 'Zip Code',
                    zipcoderequired: 'Zip Code Required',
                    zipcodeLength: 'Zip code should not more than 9 digits',
                    username: 'User Name',
                    usernamerequired: 'User Name Required',
                    password: 'Password',
                    passwordrequired: 'Password Required',
                    passwordMinLength: 'Minimun 6 characters are required.',
                    passwordMaxLength: 'Maximum 20 characters are allowed.',
                    userrole: 'User Role',
                    userrolerequired: 'User Role Required',
                    hourlylabourrate: 'Hourly Labour Rate',
                    hourlylabourraterequired: 'Hourly Labour Rate Required',
                    adduserrole: 'Add User Role',
                    newemployeesavedsuccess: 'Employee Details Saved Successfully.',
                    employeealreadyexist: 'Employee already exist.',
                    headingemployeelist: 'Employee List',
                    edit: 'Edit',
                    newemployeedeletesuccess: 'Employee deleted successfully.',
                    employeedeactivated: 'Employee inactivated successfully.',
                    employeeactivated: 'Employee activated successfully.',
                    employeehavetasks: 'Can not delete this employee. Having task assigned.',
                    employeehavetasksForInactivate: 'Can not inactivate this employee. Having task assigned.',
                    notinactivated: 'Can not inactivate this employee. Having task assigned.',
                    notactivated: 'Can not inactivate this employee. Having task assigned.',
                    noupdate: 'Can not update this employee. Might be it does not exist.',
                    duplicatefirstname: 'First name already exists',
                    duplicatelastname: 'Last name already exists',
                    duplicateemail: 'Primary email already exists',
                    duplicateusername: 'Username already exists',
                    officephoneLength: 'Maximum 15 digits are allowed',
                    sameEmailAddr: 'Secondary email id can not be same as primary.'
                },

                addnewrole: {
                    enterrole: 'Enter Role',
                    rolerequired: 'Role Required',
                    enterdescription: 'Enter Description',
                    descriptionrequired: 'Description Required',
                    newuserrolesavedsuccess: 'New User Role Saved Successfully.',
                    useralreadyexist: 'User Already Exist'
                },

                addnewgenetics: {
                    geneticsName: 'Binomial Name ',
                    geneticsrequired: 'Binomial Name  Required',
                    geneticsLength: 'Shoukd not be more than 50 characters.',
                    enterdescription: 'Binomial  Description',
                    descriptionrequired: 'Description Required',
                    newGeneticseSavedSuccess: 'Species saved successfully.',
                    geneticsAlreadyExist: 'Species already exist',
                    newGeneticsSavedSuccess: 'New Species Saved Successfully.',
                    noupdate: 'Can not update this Species. Might be it does not exist.',
                    geneticsDeletedSuccess: 'Species deleted successfully.',
                    geneticsInactivateSuccess: 'Species inactivaed successfully.',
                    geneticsActivateSuccess: 'Species activaed successfully.',
                    geneticsIsAssigned: 'Can not delete this Species. It is in use.',
                    notinactivated: 'Can not inactivate this Species. Might be it does not exist.',
                    notdeleted: 'Can not delete this Species. Might be it does not exist.',
                    strainIsInactive: 'Can not activate this Species. May be Cultivar  is inactive.'
                },
                tppPackageType: {
                    pageheading: 'Add New TPP Package Type',
                    // tpp: 'TP Processor Name',
                    tpp: 'TP Processor',
                    tpprequired: 'Select TP Processor',
                    // packagetype: 'Package Type Name',
                    packagetype: 'Package Type',
                    packagetyperequired: 'Package Type Required',
                    packagetypeLength: 'Must not more than 50 charachters',
                    description: 'Package Type Description',
                    descriptionLength: 'Must not more than 100 charachters',
                    listheading: 'TPP Package Type List',
                    savedsuccess: 'TPP package type saved successfully.',
                    alreadyexist: 'This TPP package type already exist',
                    tpppackagetypeinuse: 'Can not delete this package type. It is in use.',
                    cannotinsert: 'Can not save package type details. Might be it is not available now. Please check.',
                    deletesuccess: 'TPP package type deleted successfully.',
                    deactivatesuccess: 'TPP Package type inactivated successfully.',
                    activatesuccess: 'TPP Package type activated successfully.',
                    tppnotpresent: 'TP processor is deleted or is inactive',
                    noupdate: 'Can not update this TPP package type. Might be it does not exist.',
                    notactivated: 'Can not activate this TPP package type. Might be it does not exist.',
                    notinactivated: 'Can not inactivate this TPP package type. Might be it does not exist.',
                    notdeleted: 'Can not delete this TPP package type. Might be it does not exist.'
                },
                createNewClient:
                {
                    clientName: 'Client'
                },

                // Added by Devdan :: 03-Oct-2018 :: Resources for Task Setting Page
                taskSetting: {
                    taskType: 'Task Name',
                    isReview: 'Is Review',
                    isNotification: 'Is Notification',
                    taskList: 'Task List',
                    taskTyperequired: 'Please Select Task',
                    savedsuccess: 'Task settings saved successfully.',
                    updatesuccess: 'Task settings updated successfully.',
                    alreadyexist: 'Task setting already exist',
                    notexists: 'Can not delete task setting. Might be it does not exist.'
                },
                clientMaster:
                {
                    header: 'Retailer Accounts',
                    clientName: 'Retailer',
                    clientType: 'Type',
                    accountNo: 'Account#',
                    licenseId: 'License ID',
                    contractPerson: 'Contact',
                    phoneNo: 'Number',
                    cityName: 'City',
                    edit: 'Edit',
                    clientAccounts: 'Retailer Accounts',
                    createClient: 'Create Retailer',
                    name: 'Name',
                    clientlist: 'Retailer List'
                },
                createNew1Client:
                {
                    createNewClient: 'Create New Retailer',
                    save: 'Save',
                    cancel: 'Cancel',
                    applicationmsg: 'Application Message',
                    clientName: 'Retailer Name',
                    customerType: 'Retailer Type',
                    ubiNo: 'UBI No',
                    isActive: 'Active',
                    cdtfaPermit: 'CDTFA Permit',
                    licenseId: 'License ID',
                    accountNo: 'Account#',
                    faxNo: 'Fax Number',
                    mobileNo: 'Mobile Number',
                    officeNo: 'Office Number',
                    shippingAddress: 'Shipping Address',
                    billingAddress: 'Billing Address',
                    addressLine1: 'Address Line 1',
                    addressLine2: 'Address Line 2',
                    addressLine3: 'Address Line 3',
                    countryName: 'Country Name',
                    stateName: 'State Name',
                    cityName: 'City Name',
                    zipCode: 'Zip Code',
                    isShippingAddressSame: 'Shipping information same as billing information',
                    clinentContact: 'Retailer Contact',
                    contactFirstName: 'First name',
                    contactLastName: 'Last Name',
                    contactJobTitle: 'Job Title',
                    contactPrimaryPhone: 'Primary Phone' ,
                    contactSecondaryPhone: 'Secondary Phone',
                    clientPhoneType: 'Phone Type',
                    contactPrimaryEmail: 'Primary Email',
                    contactSecondaryEmail: 'Secondary Email',
                    addMoreContacts: 'Add More Contacts',
                    contact: 'Contact',
                    emailInvalid: 'Invalid Email Address',
                    accountNumber: 'Account Number',
                    licenses: 'License',
                    workNo: 'Work Number',
                    fax: 'Fax Number',
                    deleteContact: 'Delete Contact',
                    clientnotes: 'Retailer Notes',
                    clientNameRequired: 'Retailer Name Required',
                    customerTypeRequired: 'Select Retailer Type',
                    licenseIdRequired: 'License ID Required',
                    officeNoRequired: 'Office Number or Mobile Number Required',
                    addressLine1required: 'Address Line 1 Required',
                    countryNameRequred: 'Select Country',
                    stateNameRequried: 'Select State',
                    cityNameRequired: 'Select City',
                    zipCodeRequired: 'Select Zip Code',
                    contactFirstNameRequired: 'First Name Required',
                    contactLastNameRequired: 'Last Name Required',
                    jobTitleRequired: 'Job Title Required',
                    primaryEmailRequired: 'Primary Email Required',
                    primaryPhoneRequired: 'Primary Phone Required',
                    primaryPhonetypeRequired: 'Select Phone Type',
                    success: 'Retailer account created successfully.',
                    exists: 'Customer account already exists',
                    duplicate: 'Duplicate Customer Name.',
                    mindigitsize: 'Minimum 10 Digits Required',
                    nocommentsavb: 'No comments available.',
                    deleteconfirmation: ' Are you sure, you want to delete contact?',
                    yes: 'Yes',
                    no: 'No',
                    contactdeletedsuccess: 'Contact deleted successfully.',
                    primarysecondaryEmailsame: 'Primary Email and Secondary Email should not be same.',
                    primarysecondaryPhonesame: 'Primary Phone and Secondary Phone should not be same.',
                    addnewnotes: 'Add new note',
                    contactupdatesuccess: 'Retailer updated successfully.',
                    activeClient: 'Are you sure you want to re-open this account?',
                    inActiveClient: 'Are you sure you want to close this account?',
                    licenseNoDuplicate: 'Duplicate License ID',
                    clientNameDuplicate: 'Duplicate Client Name',
                    atleatonecontact: 'Atleast one contact person required',
                    primeCheckbox: 'Please select atleast primary checkbox for contact.',
                    autogenerate: 'This is auto genarate after saving record',
                    retailerDelete: 'Retailer is already deleted',
                    createclient: 'Create Retailer',
                    ubiRequired: 'UBI No required'
                } ,
                roleAccessPermisssion: {
                    roleaddedsuccs: 'Access permission updated successfuly.',
                    atlistoneRole: 'Please select at least on page to give permission.',
                    selectRole: 'Please select User Role.',
                    roleaccesspermossion: 'Role Access Permission',
                    save: 'Save',
                    clear: 'Clear',
                    userRoles: 'User Role'
                },
                erroraccessdenied: {
                   oops: 'Oops!',
                   errormsg: 'You do not have permission to access the page that you requested, Please contact administrator.',
                   rediretmsg: 'To redirect home page',
                   clickhere: 'click here.'
                },
                addnewtasktype:{
                    Pageheading:'Add New Task',
                    pageheading: 'New Task',
                    entertasktype: 'Task Category',
                    tasktype: 'Task Type',
                    tasktyperequired: 'Select Task Type',
                    entertask: 'Task Type',
                    TaskType: 'Tasktype',
                    Taskrequired: 'Task  Required',
                    TaskLength: 'Must not more than 50 charachters',
                    description: 'Task Description',
                    newTasksavedsuccess: 'Task saved successfully.',
                    taskalreadyexist: 'This task already exist',
                    taskActivated: 'Task activated successfully.',
                    taskInactivated: 'Task inactivated successfully.',
                    deletetaskmsg: 'Do you want to delete this task?',
                    activetaskmsg: 'Do you want to activate this task?',
                    deactivatetaskmsg: 'Do you want to inactivate this task?',
                    TaskDeletedSuccess: 'Task deleted successfully.',
                },
                addNewSkew: {
                    skewType: 'Skew Type',
                    skewName: 'Skew Name',
                },
                addNewRoomType:{
                    pageheading:'New Room Type',
                    enterroomtype:'Room Type Name',
                    RoomTypeRequired:'Room Type Required',
                    RoomTypeLength:"Must not more than 50 Characters",
                    enterdescription:'Room Type Description',
                    descriptionrequired:'Description type required',
                    descriptionLength:'Must not more than 500 characters',
                    newRoomTypeSavedSuccess:'Room type saved successfully',
                    newRoomTypeInactivated:'Room type Inactivated successfully',
                    newRoomTypeActivated:'Room Type Activated successfully',
                    newRoomTypeDeleted:'Room type Deleted Scuccessfully',
                    RoomTypeAlreadyExists:'Room Type already Exists',
                    RoomTypeAssigned:'Can not delete this RoomType. It is in use',
                    noupdate:'Can not update this Room Type.Might be it does not exist',
                    notactivated:'Can not activate this Room Type.Might be it deos not exist',
                    notinactivated:'Can not Inactivate this Room Type .Might be it does not exist',
                    notdeleted:'Can not delete this RoomType.Might be it does not exist',
                    RoomtypeIsInactive:'Can not activate this RoomType.May be Room is Inactive'
                },
                addNewzones:{
                    pageheading:'New Zone',
                    enterzone:'Zone Name',
                    ZoneRequired:'Zone Required',
                    ZoneLength:"Must not more than 50 Characters",
                    enterdescription:'Zone Description',
                    descriptionrequired:'Description type required',
                    descriptionLength:'Must not more than 500 characters',
                    newZoneSavedSuccess:'Zone saved successfully',
                    newZoneInactivated:'Zone Inactivated successfully',
                    newZoneActivated:'Zone Activated successfully',
                    newZoneDeleted:'Zone Deleted Scuccessfully',
                    ZoneAlreadyExists:'Zone already Exists',
                    ZoneAssigned:'Can not delete this Zone. It is in use',
                    noupdate:'Can not update this Zone.Might be it does not exist',
                    notactivated:'Can not activate this Zone.Might be it deos not exist',
                    notinactivated:'Can not Inactivate this Zone .Might be it does not exist',
                    notdeleted:'Can not delete this Zone.Might be it does not exist',
                    ZoneIsInactive:'Can not activate this Zone.May be Room is Inactive',
                    RoomName:'Room Name',
                    RoomRequired:'Room is required'

                },
                addNewRooms:{
                    pageheading:'New Room',
                    enterRoomType:'Room Type',
                    RoomTypeRequired:'Room Type Required',
                    Roomypenotpresent: 'Room type is deleted or is inactive.',
                    Zone:'Zone',
                    viewaddZones: 'View/Add Zones',
                    enterRoom:'Room Name',
                    RoomRequired:'Room Required',
                    RoomLength:"Must not more than 50 Characters",
                    enterdescription:'Room Description',
                    descriptionrequired:'Description type required',
                    descriptionLength:'Must not more than 500 characters',
                    newRoomSavedSuccess:'Room saved successfully',
                    newRoomInactivated:'Room Inactivated successfully',
                    newRoomActivated:'Room Activated successfully',
                    newRoomDeleted:'Room Deleted Scuccessfully',
                    RoomAlreadyExists:'Room already Exists',
                    RoomAssigned:'Can not delete this Room. It is in use',
                    noupdate:'Can not update this Room.Might be it does not exist',
                    notactivated:'Can not activate this Room.Might be it deos not exist',
                    notinactivated:'Can not Inactivate this Room .Might be it does not exist',
                    notdeleted:'Can not delete this Room.Might be it does not exist',
                    RoomIsInactive:'Can not activate this Room.May be Room is Inactive',
                    deleteRoomMsg: 'Do you want to delete this Room?',
                    activeRoomMsg: 'Do you want to activate this Room?',
                    deactivateRoomMsg: 'Do you want to inactivate this Room?',
                    RoomDeletedSuccess: 'Room deleted successfully.',
                    roomtypeOrZonesIsInactive: 'Can not activate this Room. Might be Room type or Zones is inactive.',
                },
                addNewRoomTable:{
                    pageheading:'New Room Table',
                    enterRoom:'Room Name',
                    RoomRequired:'Room Required',
                    Roomnotpresent: 'Room is deleted or is inactive.',
                    Zone:'Zone',
                    Zonerequired: 'Zone required',
                    viewaddZones: 'View/Add Zones',
                    enterRoomTable:'RoomTable Name',
                    RoomTableRequired:'RoomTable Required',
                    RoomTableLength:"Must not more than 50 Characters",
                    enterdescription:'RoomTable Description',
                    descriptionrequired:'Description type required',
                    descriptionLength:'Must not more than 500 characters',
                    newRoomTableSavedSuccess:'Room Table saved successfully',
                    newRoomTableInactivated:'Room Table Inactivated successfully',
                    newRoomTableActivated:'Room Table Activated successfully',
                    newRoomTableDeleted:'Room Table Deleted Scuccessfully',
                    RoomTableAlreadyExists:'Room Table already Exists',
                    RoomTableAssigned:'Can not delete this Room Tabale. It is in use',
                    noupdate:'Can not update this Room Table.Might be it does not exist',
                    notactivated:'Can not activate this Room Table.Might be it deos not exist',
                    notinactivated:'Can not Inactivate this Room Table .Might be it does not exist',
                    notdeleted:'Can not delete this Room Table.Might be it does not exist',
                    RoomTableIsInactive:'Can not activate this Room Table.May be Room Table is Inactive',
                    deleteRoomTableMsg: 'Do you want to delete this Room Table?',
                    activeRoomTableMsg: 'Do you want to activate this Room Table?',
                    deactivateRoomTableMsg: 'Do you want to inactivate this Room Table?',
                    RoomTableDeletedSuccess: 'Room Tbale deleted successfully.',
                    RoomOrZonesIsInactive: 'Can not activate this Room Table. Might be Room  or Zones is inactive.',
                    Lenghtlabel:'Length',
                    lengthRequired:"Length Required",
                    Breadthlabel:'Breadth',
                    widthrequired:'Breadth Required',
                    Heightlabel:'Height',
                    HeightRequired:'Height required'
                },
                addNewFields:{
                    pageheading:'New Field',
                    enterFieldType:'Field Type',
                    FieldRequired:'Field  Required',
                    // Roomypenotpresent: 'Field type is deleted or is inactive.',
                    // Zone:'Zone',
                    // viewaddZones: 'View/Add Zones',
                    enterAcres:'Acres',
                    AcresRequired:'Acres Required',
                    // RoomLength:"Must not more than 50 Characters",
                    enterdescription:'Field Description',
                    descriptionrequired:'Description type required',
                    descriptionLength:'Must not more than 500 characters',
                    newFieldSavedSuccess:'Field saved successfully',
                    newFieldInactivated:'Field Inactivated successfully',
                    newFieldActivated:'Field Activated successfully',
                    newFieldDeleted:'Field Deleted Scuccessfully',
                    FieldAlreadyExists:'Field already Exists',
                    FieldAssigned:'Can not delete this Field. It is in use',
                    noupdate:'Can not update this Field.Might be it does not exist',
                    notactivated:'Can not activate this Field.Might be it deos not exist',
                    notinactivated:'Can not Inactivate this Field .Might be it does not exist',
                    notdeleted:'Can not delete this Field.Might be it does not exist',
                    FieldIsInactive:'Can not activate this Field.May be Field is Inactive',
                    deleteFieldMsg: 'Do you want to delete this Field?',
                    activeFieldMsg: 'Do you want to activate this Field?',
                    deactivateFieldMsg: 'Do you want to inactivate this Field?',
                    FieldDeletedSuccess: 'Field deleted successfully.',
                    updated:'Field Updated Successfully'
                    // FieldtypeOrZonesIsInactive: 'Can not activate this Field. Might be Field is inactive.',
                },
            }
        };
    }
}
